package at.study.redmine.model.role;

public enum Permissions {
    ADD_PROJECT(""),
    EDIT_PROJECT(""),
    CLOSE_PROJECT(""),
    SELECT_PROJECT_MODULES(""),
    MANAGE_MEMBERS(""),
    MANAGE_VERSIONS(""),
    ADD_SUBPROJECTS(""),
    MANAGE_PUBLIC_QUERIES(""),
    SAVE_QUERIES(""),
    VIEW_MESSAGES(""),
    ADD_MESSAGES(""),
    EDIT_MESSAGES(""),
    EDIT_OWN_MESSAGES(""),
    DELETE_MESSAGES(""),
    DELETE_OWN_MESSAGES(""),
    MANAGE_BOARDS(""),
    VIEW_CALENDAR(""),
    VIEW_DOCUMENTS(""),
    ADD_DOCUMENTS(""),
    EDIT_DOCUMENTS(""),
    DELETE_DOCUMENTS(""),
    VIEW_FILES(""),
    MANAGE_FILES(""),
    VIEW_GANTT(""),
    VIEW_ISSUES("Просмотр задач"),
    ADD_ISSUES(""),
    EDIT_ISSUES(""),
    EDIT_OWN_ISSUES(""),
    COPY_ISSUES(""),
    MANAGE_ISSUE_RELATIONS(""),
    MANAGE_SUBTASKS(""),
    SET_ISSUES_PRIVATE(""),
    SET_OWN_ISSUES_PRIVATE(""),
    ADD_ISSUE_NOTES(""),
    EDIT_ISSUE_NOTES(""),
    EDIT_OWN_ISSUE_NOTES(""),
    VIEW_PRIVATE_NOTES(""),
    SET_NOTES_PRIVATE(""),
    DELETE_ISSUES(""),
    VIEW_ISSUE_WATCHERS(""),
    ADD_ISSUE_WATCHERS(""),
    DELETE_ISSUE_WATCHERS(""),
    IMPORT_ISSUES(""),
    MANAGE_CATEGORIES(""),
    VIEW_NEWS(""),
    MANAGE_NEWS(""),
    COMMENT_NEWS(""),
    VIEW_CHANGESETS(""),
    BROWSE_REPOSITORY(""),
    COMMIT_ACCESS(""),
    MANAGE_RELATED_ISSUES(""),
    MANAGE_REPOSITORY(""),
    VIEW_TIME_ENTRIES(""),
    LOG_TIME(""),
    EDIT_TIME_ENTRIES(""),
    EDIT_OWN_TIME_ENTRIES(""),
    MANAGE_PROJECT_ACTIVITIES(""),
    LOG_TIME_FOR_OTHER_USERS(""),
    IMPORT_TIME_ENTRIES(""),
    VIEW_WIKI_PAGES(""),
    VIEW_WIKI_EDITS(""),
    EXPORT_WIKI_PAGES(""),
    EDIT_WIKI_PAGES(""),
    RENAME_WIKI_PAGES(""),
    DELETE_WIKI_PAGES(""),
    DELETE_WIKI_PAGES_ATTACHMENTS(""),
    PROTECT_WIKI_PAGES(""),
    MANAGE_WIKI("");

    private final String description;

    Permissions(String description) {
        this.description = description;
    }
}

